ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER ECOMMERCEAPI IDENTIFIED BY ecommerce123;
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO ECOMMERCEAPI;
ALTER USER ECOMMERCEAPI DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO ECOMMERCEAPI;
COMMIT;
EXIT;
