-- Create ECOMMERCEAPI user for the application
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- Create user if it doesn't exist
DECLARE
  v_user_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_user_exists FROM dba_users WHERE username = 'ECOMMERCEAPI';
  IF v_user_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER ECOMMERCEAPI IDENTIFIED BY ecommerce123';
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO ECOMMERCEAPI';
    EXECUTE IMMEDIATE 'ALTER USER ECOMMERCEAPI DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO ECOMMERCEAPI';
    DBMS_OUTPUT.PUT_LINE('User ECOMMERCEAPI created successfully');
  ELSE
    DBMS_OUTPUT.PUT_LINE('User ECOMMERCEAPI already exists');
  END IF;
END;
/

-- Verify user was created
SELECT username FROM dba_users WHERE username = 'ECOMMERCEAPI';

COMMIT;
