spring.application.name=ecommerce.api

# ORACLE DATASOURCE
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=ECOMMERCEAPI
spring.datasource.password=1234

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.connection.driver_class=oracle.jdbc.OracleDriver

# Server Configuration
server.port=8080
server.servlet.context-path=/api

# JWT Configuration
app.jwtSecret=${JWT_SECRET:ecommerceSecretKeyForJWTTokenGenerationAndValidation2024}
app.jwtExpirationMs=86400000

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true